resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:9f55c781c43ee7b41eac30004f42f69e36c1f7d844bee2f057547688c9e04026
  name: controller
  newName: 007635145730.dkr.ecr.ap-northeast-2.amazonaws.com/gpu-platform-operator
