# This rule is not used by the project gpu-platform-control-plane itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over platform.lkhun9311.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: inferencedeployment-admin-role
rules:
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - inferencedeployments
  verbs:
  - '*'
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - inferencedeployments/status
  verbs:
  - get
