# This rule is not used by the project gpu-platform-control-plane itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to platform.lkhun9311.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-platform-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: mltrainingjob-viewer-role
rules:
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - mltrainingjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - mltrainingjobs/status
  verbs:
  - get
