---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - nodehealths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - nodehealths/finalizers
  verbs:
  - update
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - nodehealths/status
  verbs:
  - get
  - patch
  - update
