---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - gpuquotapolicies
  - mltrainingjobs
  - nodehealths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - gpuquotapolicies/finalizers
  - mltrainingjobs/finalizers
  - nodehealths/finalizers
  verbs:
  - update
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - gpuquotapolicies/status
  - inferencedeployments/status
  - mltrainingjobs/status
  - nodehealths/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.lkhun9311.github.io
  resources:
  - inferencedeployments
  verbs:
  - get
  - list
  - watch
