/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"flag"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/lkhun9311/gpu-mlops-platform-control-plane/internal/bench"
)

// prepareTraces builds every trace an M5-b run will replay, measures the served tokenizer's counts once, and
// finalises the manifests against the FINISHED files.
//
// # WHY THIS EXISTS
//
// The runner used to generate one canonical trace, stamp it with exact input-token counts, and then generate a
// SECOND trace per arm and repetition inside the replay loop -- and replay that one. So the stamped file was
// never replayed: every row that reached the report carried ExactInputTokens: 0, and the admission-match
// criterion, which the design defines over those counts, could not be evaluated for any paid run.
//
// It was worse than a wasted measurement. Stamping rewrites the trace in place, and the canonical manifest's
// checksum had already been computed over the PRE-stamping bytes, so that manifest was permanently unusable
// (LoadManifest verifies the checksum unconditionally). Nothing noticed, because the replay loop overwrote the
// manifests with fresh ones.
//
// The ordering is therefore the whole point: generate, stamp, verify, derive, and only then checksum. A
// manifest written before the trace is final is a manifest that will be refused or, worse, one whose checksum
// blesses bytes nobody measured.
//
// R1 is DERIVED rather than regenerated. It is the same two-tenant trace with the contender rows filtered out,
// which is what keeps premium arriving on the identical schedule it has in the contended arms -- and filtering
// preserves the measured counts, where regenerating would discard them.
func prepareTraces(args []string) error {
	fs := flag.NewFlagSet("prepare-traces", flag.ExitOnError)
	canonical := fs.String("trace", "", "canonical trace file, already generated by gen-trace (required)")
	outDir := fs.String("out-dir", "", "directory to write the per-arm traces and manifests into (required)")
	arms := fs.String("arms", "", "comma-separated arms to prepare, e.g. R1,off,static-cap,kv-aware (required)")
	reps := fs.Int("reps", 0, "repetitions per arm (required)")
	study := fs.String("study", bench.StudyM5BGateway, "pre-registered study the manifests belong to")
	gatewayURL := fs.String("gateway-url", "", "gateway URL the manifests record (required)")
	model := fs.String("model", "", "model name the engine serves (required)")
	timeoutMs := fs.Int("timeout-ms", 0, "per-request timeout the manifests record (required)")
	seed := fs.Int64("seed", 0, "trace generator seed the canonical trace was built with, recorded for provenance")
	matchTol := fs.String("match-tolerance", "", "admission-match tolerance the manifests record (required)")
	longThreshold := fs.Int("long-threshold", 4096, "eligible-population threshold the manifests record")
	gatewaySHA := fs.String("gateway-sha", "", "gateway build the manifests record")
	gatewayImage := fs.String("gateway-image", "", "gateway image reference, digest-pinned")
	engineImage := fs.String("engine-image", "", "engine image reference, digest-pinned")
	// The tokenizer revision, needed here for the same reason as in gen-trace.
	//
	// There are TWO paths that write a manifest -- gen-trace and this one -- and RequireProvenance now demands
	// the revision from both. Adding the flag to only one would leave m5b refused at its first replay, with
	// both engines already up, which is the most expensive place in this project to learn anything.
	tokenizerRev := fs.String("tokenizer-rev", "",
		"revision of the served model whose tokenizer the estimate was calibrated against (40 lowercase hex)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	switch {
	case *canonical == "":
		return fmt.Errorf("-trace is required")
	case *outDir == "":
		return fmt.Errorf("-out-dir is required")
	case *arms == "":
		return fmt.Errorf("-arms is required")
	case *reps <= 0:
		return fmt.Errorf("-reps must be positive")
	case *gatewayURL == "" || *model == "" || *matchTol == "":
		return fmt.Errorf("-gateway-url, -model and -match-tolerance are all required")
	case *timeoutMs <= 0:
		return fmt.Errorf("-timeout-ms must be positive")
	}

	// readTrace rather than readTraceFile: the two are the same operation under two names in this package
	// (exacttokens.go:104 and helpers.go:61), and this command is the pair of stamp-exact-tokens, which uses
	// the former. Collapsing them is a separate tidy-up; picking the one its sibling uses keeps this change
	// about the trace handoff.
	rows, err := readTrace(*canonical)
	if err != nil {
		return err
	}
	if len(rows) == 0 {
		return fmt.Errorf("the canonical trace %s has no rows", *canonical)
	}

	// Every row must carry a measured count, and this refusal is the reason the command exists.
	//
	// Publishing manifests for an unstamped trace would hand the replay loop something that looks ready and
	// produces evidence the admission-match criterion cannot be scored from. The check is on EVERY row rather
	// than on a sample, because the fraction's denominator includes the refused ones.
	missing := 0
	for _, r := range rows {
		if r.ExactInputTokens <= 0 {
			missing++
		}
	}
	if missing > 0 {
		return fmt.Errorf("%d of %d rows in %s carry no measured input-token count, so no manifest is published: run stamp-exact-tokens against this trace first, because the admission-match criterion is defined over the served tokenizer's own count and a run replayed from these rows could not be scored against it",
			missing, len(rows), *canonical)
	}

	armList := strings.Split(*arms, ",")
	for i := range armList {
		armList[i] = strings.TrimSpace(armList[i])
	}

	// One trace file per arm, and repetitions share it.
	//
	// The contended arms replay byte-identical traffic by design -- that is what makes their comparison a
	// comparison -- so they share one file and one checksum. R1 gets its own because its population is a
	// subset, and `report` refuses repetitions whose checksums differ, which is what would catch a slip here.
	tracePathFor := map[string]string{}
	// Kept per arm, because the manifest loop below needs the ROWS and not only the path.
	//
	// The isolated baseline's rows are a subset -- premium only -- so a manifest built from the canonical
	// trace would claim a contender prompt length for an arm that was never sent one.
	rowsFor := map[string][]bench.TraceRow{}
	for _, arm := range armList {
		out := filepath.Join(*outDir, "trace-"+arm+".jsonl")
		armRows := rows
		if bench.IsIsolatedBaseline(arm) {
			// Filtered, not regenerated: the indices, offsets and measured counts all survive.
			premiumOnly := make([]bench.TraceRow, 0, len(rows))
			for _, r := range rows {
				if !r.IsNoisy {
					premiumOnly = append(premiumOnly, r)
				}
			}
			if len(premiumOnly) == 0 {
				return fmt.Errorf("arm %s is an isolated baseline but the canonical trace has no premium rows to derive it from", arm)
			}
			armRows = premiumOnly
		}
		if err := writeTrace(out, armRows); err != nil {
			return err
		}
		tracePathFor[arm] = out
		rowsFor[arm] = armRows
		fmt.Printf("%-12s %6d rows -> %s\n", arm, len(armRows), out)
	}

	// Checksums come from the files as they now stand on disk, after every write above.
	for _, arm := range armList {
		sum, cerr := bench.ChecksumFile(tracePathFor[arm])
		if cerr != nil {
			return fmt.Errorf("checksum %s: %w", tracePathFor[arm], cerr)
		}
		for rep := 1; rep <= *reps; rep++ {
			manifestOut := filepath.Join(*outDir, fmt.Sprintf("manifest-%s-%d.yaml", arm, rep))
			m := bench.RunManifest{
				SchemaVersion:   "v2",
				PromptCorpusSHA: bench.PromptCorpusSHA256,
				Study:           *study,
				Arm:             arm,
				GatewayURL:      *gatewayURL,
				TracePath:       traceRefFor(manifestOut, tracePathFor[arm]),
				TraceChecksum:   sum,
				Model:           *model,
				TimeoutMs:       *timeoutMs,
				TimeoutScope:    bench.TimeoutScopeWholeRequest,
				Seed:            *seed,
				PrimaryEndpoint: "ttft_p99",
				MatchTolerance:  *matchTol,
				LongThreshold:   *longThreshold,
				GatewaySHA:      *gatewaySHA,
				TokenizerRev:    *tokenizerRev,
				PromptLenChars:  bench.PromptLenCharsByTenant(rowsFor[arm]),
			}
			for role, ref := range map[string]string{"gateway": *gatewayImage, "engine": *engineImage} {
				if ref == "" {
					continue
				}
				if m.ImageDigests == nil {
					m.ImageDigests = map[string]string{}
				}
				m.ImageDigests[role] = ref
			}
			if err := writeManifest(manifestOut, m); err != nil {
				return err
			}
		}
	}
	fmt.Printf("prepared %d arm(s) x %d repetition(s); every row carries a measured input-token count\n", len(armList), *reps)
	return nil
}
